[build-system]
requires = [
    "black",
    "click",
    "Cython",
    "matplotlib",
    "netcdf4",
    "networkx",
    "numpy",
    "pandas",
    "plotly",
    "scipy",
    "setuptools",
    "typing_extensions",
    "wheel",
    "wrapt",
    "xmlschema",
]
